"<HTML> <HEAD>",
"<TITLE>NEWFIRM DHS -- On-Line Help Summary</TITLE>",
"</HEAD> <BODY>",
"<H2>Welcome to DHS Supervisor V1.0</H2>",
"",
"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas massa. Ut",
"eu est at lorem sollicitudin mattis. Ut erat. Vivamus rutrum, leo at viverra",
"venenatis, risus nisl fringilla felis, dignissim pretium sapien ipsum sit",
"amet tellus. In faucibus, nulla in commodo congue, tellus augue luctus magna,",
"sed dignissim magna tellus et tellus. Pellentesque habitant morbi tristique",
"senectus et netus et malesuada fames ac turpis egestas. Ut commodo. Nulla",
"placerat. Nulla facilisi. Vivamus non diam bibendum sapien porta vestibulum.",
"Aenean nec mauris nec nibh consectetuer varius. Maecenas purus risus,",
"tristique auctor, lacinia sit amet, accumsan a, sem. Donec augue enim,",
"pretium quis, ornare et, consectetuer ut, lectus. Nam bibendum dignissim leo.",
"Integer ornare, elit et facilisis pharetra, massa orci venenatis orci, non",
"sodales diam mi egestas augue. Pellentesque odio turpis, rhoncus vitae,",
"vestibulum ac, porttitor id, lectus. Donec pulvinar dolor ut tellus. Cum",
"sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus",
"mus. Aenean nunc lacus, molestie vel, iaculis eu, elementum vel, quam.",
"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere",
"cubilia Curae;",
"",
"",
"More <a href=#toc>detailed help</a> is available on the following topics:",
"<dl><dl>",
"<dt>Basic Usage:</dt>",
"<ul>",
"<li><A HREF=\"#basic\">Getting Started</A> -- The basics. </li>",
"<li><A HREF=\"#gui\">GUI Overview</A> -- What it looks like. </li>",
"</ul></dl></dl>",
"<dl><dl>",
"<dt>Advanced Features:</dt>",
"<ul>",
"<li><A HREF=\"#comline\">Command-line Options</A> -- Startup flags. </li>",
"<li><A HREF=\"#client\">Client Connections</A> -- Use as a display server. </li>",
"<li><A HREF=\"#tclshell\">TclShell</A> -- Expert-mode interactive shell.</li>",
"</ul></dl></dl>",
"",
"</BODY>",
"</HTML>",
