#!/bin/csh -f


set i = 0
loop:
    echo "Test Iteration $i"
    /bin/rm -f /home/data/*
    ./exp -loop 10 -delay 10

    sleep 30

    set i = `expr $i + 1`
    if ($i < 256) then
	goto loop
    endif

