#!/bin/csh -f

echo "Shutting down PXF...."
/ndhs/bin/dhscmd -group PXF -quit		>& /dev/null
echo "Shutting down SMC Managers...."
/ndhs/bin/dhscmd -group SMCMgr -quit		>& /dev/null
echo "Shutting down Collectors...."
/ndhs/bin/dhscmd -group Collector -quit		>& /dev/null
echo "Shutting down DCA...."
/ndhs/bin/dhscmd -group NF-DCA -quit		>& /dev/null
echo "Shutting down Supervisor...."
/ndhs/bin/dhscmd -group Super -quit		>& /dev/null

echo "Killing VNC Servers...."
vncserver -kill :1 				>& /dev/null
vncserver -kill :2 				>& /dev/null
vncserver -kill :3 				>& /dev/null
vncserver -kill :4 				>& /dev/null
vncserver -kill :5 				>& /dev/null
vncserver -kill :6 				>& /dev/null
echo "Done."
